// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using deeplynx.datalayer.Models;

#nullable disable

namespace deeplynx.datalayer.Migrations
{
    [DbContext(typeof(DeeplynxContext))]
    [Migration("20250902174045_CreatePermissions")]
    partial class CreatePermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.5.25277.114")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("GroupId", "UserId")
                        .HasName("group_users_pkey");

                    b.HasIndex(new[] { "GroupId" }, "idx_group_users_group_id");

                    b.HasIndex(new[] { "UserId" }, "idx_group_users_user_id");

                    b.ToTable("group_users", "deeplynx");
                });

            modelBuilder.Entity("RecordLabel", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("record_id");

                    b.Property<long>("LabelId")
                        .HasColumnType("bigint")
                        .HasColumnName("label_id");

                    b.HasKey("RecordId", "LabelId")
                        .HasName("record_labels_pkey");

                    b.HasIndex(new[] { "LabelId" }, "idx_record_labels_label_id");

                    b.HasIndex(new[] { "RecordId" }, "idx_record_labels_record_id");

                    b.ToTable("record_labels", "deeplynx");
                });

            modelBuilder.Entity("RecordMappingTag", b =>
                {
                    b.Property<long>("RecordMappingId")
                        .HasColumnType("bigint");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.Property<long>("RecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("record_mapping_id");

                    b.HasKey("RecordMappingId", "TagId")
                        .HasName("record_mapping_tags_pkey");

                    b.HasIndex(new[] { "RecordMappingId" }, "idx_record_mapping_tags_record_mapping_id");

                    b.HasIndex(new[] { "TagId" }, "idx_record_mapping_tags_tag_id");

                    b.ToTable("record_mapping_tags", "deeplynx");
                });

            modelBuilder.Entity("RecordTag", b =>
                {
                    b.Property<long>("RecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("record_id");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.HasKey("RecordId", "TagId")
                        .HasName("record_tags_pkey");

                    b.HasIndex(new[] { "RecordId" }, "idx_record_tags_record_id");

                    b.HasIndex(new[] { "TagId" }, "idx_record_tags_tag_id");

                    b.ToTable("record_tags", "deeplynx");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("role_permissions_pkey");

                    b.HasIndex(new[] { "PermissionId" }, "idx_role_permissions_permission_id");

                    b.HasIndex(new[] { "RoleId" }, "idx_role_permissions_role_id");

                    b.ToTable("role_permissions", "deeplynx");
                });

            modelBuilder.Entity("UserProject", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.HasKey("UserId", "ProjectId")
                        .HasName("user_project_pkey");

                    b.HasIndex(new[] { "ProjectId" }, "idx_user_project_project_id");

                    b.HasIndex(new[] { "UserId" }, "idx_user_project_user_id");

                    b.ToTable("user_project", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Action", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Config")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("actions_pkey");

                    b.HasIndex(new[] { "Id" }, "idx_actions_id");

                    b.HasIndex(new[] { "ProjectId" }, "idx_project_id");

                    b.ToTable("actions", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Class", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Uuid")
                        .HasColumnType("text")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("classes_pkey");

                    b.HasIndex(new[] { "Id" }, "idx_classes_id");

                    b.HasIndex(new[] { "Name" }, "idx_classes_name");

                    b.HasIndex(new[] { "ProjectId" }, "idx_classes_project_id");

                    b.HasIndex(new[] { "Uuid" }, "idx_classes_uuid");

                    b.HasIndex(new[] { "ProjectId", "Name" }, "unique_class_name")
                        .IsUnique();

                    b.ToTable("classes", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.DataSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("Id"), 1L, null, null, null, null, null);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("BaseUri")
                        .HasColumnType("text")
                        .HasColumnName("base_uri");

                    b.Property<string>("Config")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("data_sources_pkey");

                    b.HasIndex(new[] { "Id" }, "idx_data_sources_id");

                    b.HasIndex(new[] { "ProjectId" }, "idx_data_sources_project_id");

                    b.ToTable("data_sources", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Edge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<long>("DestinationId")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_id");

                    b.Property<long?>("MappingId")
                        .HasColumnType("bigint")
                        .HasColumnName("mapping_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_id");

                    b.Property<long>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("project_id");

                    b.Property<long?>("RelationshipId")
                        .HasColumnType("bigint")
                        .HasColumnName("relationship_id");

                    b.HasKey("Id")
                        .HasName("edges_pkey");

                    b.HasIndex(new[] { "DataSourceId" }, "idx_edges_data_source_id");

                    b.HasIndex(new[] { "DestinationId" }, "idx_edges_destination_id");

                    b.HasIndex(new[] { "Id" }, "idx_edges_id");

                    b.HasIndex(new[] { "MappingId" }, "idx_edges_mapping_id");

                    b.HasIndex(new[] { "OriginId" }, "idx_edges_origin_id");

                    b.HasIndex(new[] { "ProjectId" }, "idx_edges_project_id");

                    b.HasIndex(new[] { "RelationshipId" }, "idx_edges_relationship_id");

                    b.HasIndex(new[] { "ProjectId", "OriginId", "DestinationId" }, "unique_edge_record_ids")
                        .IsUnique();

                    b.ToTable("edges", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.EdgeMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<long>("DestinationId")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_id");

                    b.Property<string>("DestinationParams")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("destination_params");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_id");

                    b.Property<string>("OriginParams")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("origin_params");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long>("RelationshipId")
                        .HasColumnType("bigint")
                        .HasColumnName("relationship_id");

                    b.HasKey("Id")
                        .HasName("edge_mappings_pkey");

                    b.HasIndex(new[] { "DataSourceId" }, "idx_edge_mappings_data_source_id");

                    b.HasIndex(new[] { "DestinationId" }, "idx_edge_mappings_destination_id");

                    b.HasIndex(new[] { "Id" }, "idx_edge_mappings_id");

                    b.HasIndex(new[] { "OriginId" }, "idx_edge_mappings_origin_id");

                    b.HasIndex(new[] { "ProjectId" }, "idx_edge_mappings_project_id");

                    b.HasIndex(new[] { "RelationshipId" }, "idx_edge_mappings_relationship_id");

                    b.ToTable("edge_mappings", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long?>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.HasKey("Id")
                        .HasName("events_pkey");

                    b.HasIndex("DataSourceId");

                    b.HasIndex(new[] { "Id" }, "idx_events_id");

                    b.HasIndex(new[] { "ProjectId" }, "idx_events_project_id");

                    b.ToTable("events", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("groups_pkey");

                    b.HasIndex(new[] { "Id" }, "idx_groups_id");

                    b.HasIndex(new[] { "OrganizationId" }, "idx_groups_organization_id");

                    b.ToTable("groups", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.HistoricalEdge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<string>("DataSourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source_name");

                    b.Property<long>("DestinationId")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_id");

                    b.Property<long>("EdgeId")
                        .HasColumnType("bigint")
                        .HasColumnName("edge_id");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<long?>("MappingId")
                        .HasColumnType("bigint")
                        .HasColumnName("mapping_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_id");

                    b.Property<long>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("project_id");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_name");

                    b.Property<long?>("RelationshipId")
                        .HasColumnType("bigint")
                        .HasColumnName("relationship_id");

                    b.Property<string>("RelationshipName")
                        .HasColumnType("text")
                        .HasColumnName("relationship_name");

                    b.HasKey("Id")
                        .HasName("historical_edges_pkey");

                    b.HasIndex(new[] { "DestinationId" }, "idx_historical_edges_destination_id");

                    b.HasIndex(new[] { "EdgeId" }, "idx_historical_edges_edge_id");

                    b.HasIndex(new[] { "Id" }, "idx_historical_edges_id");

                    b.HasIndex(new[] { "LastUpdatedAt" }, "idx_historical_edges_last_updated_at");

                    b.HasIndex(new[] { "OriginId" }, "idx_historical_edges_origin_id");

                    b.HasIndex(new[] { "RelationshipName" }, "idx_historical_edges_relationship_name");

                    b.ToTable("historical_edges", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.HistoricalRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<string>("ClassName")
                        .HasColumnType("text")
                        .HasColumnName("class_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<string>("DataSourceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source_name");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<long?>("MappingId")
                        .HasColumnType("bigint")
                        .HasColumnName("mapping_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ObjectStorageId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_storage_id");

                    b.Property<string>("ObjectStorageName")
                        .HasColumnType("text")
                        .HasColumnName("object_storage_name");

                    b.Property<string>("OriginalId")
                        .HasColumnType("text")
                        .HasColumnName("original_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_name");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<long>("RecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("record_id");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Uri")
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("historical_records_pkey");

                    b.HasIndex(new[] { "ClassName" }, "idx_historical_records_class_name");

                    b.HasIndex(new[] { "Id" }, "idx_historical_records_id");

                    b.HasIndex(new[] { "LastUpdatedAt" }, "idx_historical_records_last_updated_at");

                    b.HasIndex(new[] { "Properties" }, "idx_historical_records_properties");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Properties" }, "idx_historical_records_properties"), "gin");

                    b.HasIndex(new[] { "RecordId" }, "idx_historical_records_record_id");

                    b.ToTable("historical_records", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ObjectStorage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("Default")
                        .HasColumnType("boolean")
                        .HasColumnName("default");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("object_storage_pkey");

                    b.HasIndex("ProjectId");

                    b.HasIndex(new[] { "Id" }, "idx_object_storage_id");

                    b.ToTable("object_storages", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("organization_pkey");

                    b.HasIndex(new[] { "Id" }, "idx_organizations_id");

                    b.ToTable("organizations", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.OrganizationUser", b =>
                {
                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsOrgAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_org_admin");

                    b.HasKey("OrganizationId", "UserId")
                        .HasName("organization_user_pkey");

                    b.HasIndex(new[] { "OrganizationId" }, "idx_organization_users_organization_id");

                    b.HasIndex(new[] { "UserId" }, "idx_organization_users_user_id");

                    b.HasIndex(new[] { "OrganizationId", "UserId" }, "unique_organization_user_ids")
                        .IsUnique();

                    b.ToTable("organization_users", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Domain")
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<long?>("LabelId")
                        .HasColumnType("bigint")
                        .HasColumnName("label_id");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("permission_pkey");

                    b.HasIndex(new[] { "Id" }, "idx_permissions_id");

                    b.HasIndex(new[] { "LabelId" }, "idx_permissions_label_id");

                    b.ToTable("permissions", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config")
                        .HasDefaultValueSql("'{\"edgeRecordsMutable\":false,\"ontologyMutable\":false,\"tagsMutable\":false}'::jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("projects_pkey");

                    b.HasIndex(new[] { "Id" }, "idx_projects_id");

                    b.HasIndex(new[] { "OrganizationId" }, "idx_projects_organization_id");

                    b.ToTable("projects", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("project_members_pkey");

                    b.HasIndex(new[] { "GroupId" }, "idx_project_members_group_id");

                    b.HasIndex(new[] { "Id" }, "idx_project_members_id");

                    b.HasIndex(new[] { "ProjectId" }, "idx_project_members_project_id");

                    b.HasIndex(new[] { "RoleId" }, "idx_project_members_role_id");

                    b.HasIndex(new[] { "UserId" }, "idx_project_members_user_id");

                    b.HasIndex(new[] { "ProjectId", "GroupId", "RoleId", "UserId" }, "unique_project_member_ids")
                        .IsUnique();

                    b.ToTable("project_members", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Record", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("MappingId")
                        .HasColumnType("bigint")
                        .HasColumnName("mapping_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ObjectStorageId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_storage_id");

                    b.Property<string>("OriginalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("Uri")
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("records_pkey");

                    b.HasIndex("ObjectStorageId");

                    b.HasIndex(new[] { "ClassId" }, "idx_records_class_id");

                    b.HasIndex(new[] { "DataSourceId" }, "idx_records_data_source_id");

                    b.HasIndex(new[] { "Id" }, "idx_records_id");

                    b.HasIndex(new[] { "MappingId" }, "idx_records_mapping_id");

                    b.HasIndex(new[] { "Name" }, "idx_records_name");

                    b.HasIndex(new[] { "OriginalId" }, "idx_records_original_id");

                    b.HasIndex(new[] { "ProjectId" }, "idx_records_project_id");

                    b.HasIndex(new[] { "Properties" }, "idx_records_properties");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Properties" }, "idx_records_properties"), "gin");

                    b.HasIndex(new[] { "ProjectId", "DataSourceId", "OriginalId" }, "unique_record_original_id")
                        .IsUnique();

                    b.ToTable("records", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.RecordMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<long>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("project_id");

                    b.Property<string>("RecordParams")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("record_params");

                    b.Property<long?>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.HasKey("Id")
                        .HasName("record_mappings_pkey");

                    b.HasIndex(new[] { "ClassId" }, "idx_record_mappings_class_id");

                    b.HasIndex(new[] { "DataSourceId" }, "idx_record_mappings_data_source_id");

                    b.HasIndex(new[] { "Id" }, "idx_record_mappings_id");

                    b.HasIndex(new[] { "ProjectId" }, "idx_record_mappings_project_id");

                    b.HasIndex(new[] { "TagId" }, "idx_record_mappings_tag_id");

                    b.ToTable("record_mappings", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Relationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("DestinationId")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Uuid")
                        .HasColumnType("text")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("relationships_pkey");

                    b.HasIndex(new[] { "DestinationId" }, "idx_relationships_destination_id");

                    b.HasIndex(new[] { "Id" }, "idx_relationships_id");

                    b.HasIndex(new[] { "Name" }, "idx_relationships_name");

                    b.HasIndex(new[] { "OriginId" }, "idx_relationships_origin_id");

                    b.HasIndex(new[] { "ProjectId" }, "idx_relationships_project_id");

                    b.HasIndex(new[] { "Uuid" }, "idx_relationships_uuid");

                    b.HasIndex(new[] { "ProjectId", "Name" }, "unique_relationship_name")
                        .IsUnique();

                    b.ToTable("relationships", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Id" }, "idx_roles_id");

                    b.HasIndex(new[] { "ProjectId" }, "idx_roles_project_id");

                    b.ToTable("roles", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.SensitivityLabel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("sensitivity_labels_pkey");

                    b.HasIndex(new[] { "Id" }, "idx_sensitivity_labels_id");

                    b.HasIndex(new[] { "Name" }, "idx_sensitivity_labels_name");

                    b.HasIndex(new[] { "OrganizationId" }, "idx_sensitivity_labels_organization_id");

                    b.ToTable("sensitivity_labels", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActionId")
                        .HasColumnType("bigint")
                        .HasColumnName("action_id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long?>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Operation")
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("subscriptions_pkey");

                    b.HasIndex("ActionId");

                    b.HasIndex("DataSourceId");

                    b.HasIndex(new[] { "EntityType" }, "idx_subscriptions_entity_type");

                    b.HasIndex(new[] { "Id" }, "idx_subscriptions_id");

                    b.HasIndex(new[] { "ProjectId" }, "idx_subscriptions_project_id");

                    b.HasIndex(new[] { "UserId" }, "idx_subscriptions_user_id");

                    b.ToTable("subscriptions", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("tags_pkey");

                    b.HasIndex(new[] { "Id" }, "idx_tags_id");

                    b.HasIndex(new[] { "Name" }, "idx_tags_name");

                    b.HasIndex(new[] { "ProjectId" }, "idx_tags_project_id");

                    b.HasIndex(new[] { "ProjectId", "Name" }, "unique_tag_name")
                        .IsUnique();

                    b.ToTable("tags", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsSysAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sysadmin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "idx_users_email");

                    b.HasIndex(new[] { "Id" }, "idx_users_id");

                    b.ToTable("users", "deeplynx");
                });

            modelBuilder.Entity("GroupUser", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("group_users_user_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("group_users_group_id_fkey");
                });

            modelBuilder.Entity("RecordLabel", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.SensitivityLabel", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("record_labels_label_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Record", null)
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("record_labels_record_id_fkey");
                });

            modelBuilder.Entity("RecordMappingTag", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.RecordMapping", null)
                        .WithMany()
                        .HasForeignKey("RecordMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("record_mapping_tags_record_mapping_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("record_mapping_tags_tag_id_fkey");
                });

            modelBuilder.Entity("RecordTag", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Record", null)
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("record_tags_record_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("record_tags_tag_id_fkey");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permissions_permission_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permissions_role_id_fkey");
                });

            modelBuilder.Entity("UserProject", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_project_project_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_project_user_id_fkey");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Action", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("Actions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("actions_project_id_fkey");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Class", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("Classes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("classes_project_id_fkey");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.DataSource", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("DataSources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("data_sources_project_id_fkey");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Edge", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.DataSource", "DataSource")
                        .WithMany("Edges")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edges_data_source_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Record", "Destination")
                        .WithMany("EdgeDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edges_destination_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.EdgeMapping", "EdgeMapping")
                        .WithMany("Edges")
                        .HasForeignKey("MappingId")
                        .HasConstraintName("edges_mapping_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Record", "Origin")
                        .WithMany("EdgeOrigins")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edges_origin_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("Edges")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edges_project_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Relationship", "Relationship")
                        .WithMany("Edges")
                        .HasForeignKey("RelationshipId")
                        .HasConstraintName("edges_relationship_id_fkey");

                    b.Navigation("DataSource");

                    b.Navigation("Destination");

                    b.Navigation("EdgeMapping");

                    b.Navigation("Origin");

                    b.Navigation("Project");

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.EdgeMapping", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.DataSource", "DataSource")
                        .WithMany("EdgeMappings")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edge_mappings_data_source_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Class", "Destination")
                        .WithMany("EdgeMappingDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edge_mappings_destination_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Class", "Origin")
                        .WithMany("EdgeMappingOrigins")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edge_mappings_origin_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("EdgeMappings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edge_mappings_project_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Relationship", "Relationship")
                        .WithMany("EdgeMappings")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edge_mappings_relationship_id_fkey");

                    b.Navigation("DataSource");

                    b.Navigation("Destination");

                    b.Navigation("Origin");

                    b.Navigation("Project");

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Event", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.DataSource", "DataSource")
                        .WithMany("Events")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("events_dataSource_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("Events")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("events_project_id_fkey");

                    b.Navigation("DataSource");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Group", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Organization", "Organization")
                        .WithMany("Groups")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("groups_organization_id_fkey");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.HistoricalEdge", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Edge", "Edge")
                        .WithMany("HistoricalEdges")
                        .HasForeignKey("EdgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("historical_edges_edge_id_fkey");

                    b.Navigation("Edge");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.HistoricalRecord", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Record", "Record")
                        .WithMany("HistoricalRecords")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("historical_records_record_id_fkey");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ObjectStorage", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("ObjectStorages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("object_storage_project_id_fkey");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.OrganizationUser", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Organization", "Organization")
                        .WithMany("OrganizationUsers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("organization_users_organization_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.User", "User")
                        .WithMany("OrganizationUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("organization_users_user_id_fkey");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Permission", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.SensitivityLabel", "SensitivityLabel")
                        .WithMany("Permissions")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("permissions_label_id_fkey");

                    b.Navigation("SensitivityLabel");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Project", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("projects_organization_id_fkey");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ProjectMember", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Group", "Group")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("project_members_group_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("project_members_project_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Role", "Role")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("project_members_role_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.User", "User")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("project_members_user_id_fkey");

                    b.Navigation("Group");

                    b.Navigation("Project");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Record", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Class", "Class")
                        .WithMany("Records")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("records_class_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.DataSource", "DataSource")
                        .WithMany("Records")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_data_source_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.RecordMapping", "RecordMapping")
                        .WithMany("Records")
                        .HasForeignKey("MappingId")
                        .HasConstraintName("records_mapping_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.ObjectStorage", "ObjectStorage")
                        .WithMany("Records")
                        .HasForeignKey("ObjectStorageId")
                        .HasConstraintName("records_object_storage_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("Records")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_project_id_fkey");

                    b.Navigation("Class");

                    b.Navigation("DataSource");

                    b.Navigation("ObjectStorage");

                    b.Navigation("Project");

                    b.Navigation("RecordMapping");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.RecordMapping", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Class", "Class")
                        .WithMany("RecordMappings")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("record_mappings_class_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.DataSource", "DataSource")
                        .WithMany("RecordMappings")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("record_mapping_data_source_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("RecordMappings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("record_mappings_project_id_fkey");

                    b.Navigation("Class");

                    b.Navigation("DataSource");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Relationship", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Class", "Destination")
                        .WithMany("RelationshipDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("relationships_destination_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Class", "Origin")
                        .WithMany("RelationshipOrigins")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("relationships_origin_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("Relationships")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("relationships_project_id_fkey");

                    b.Navigation("Destination");

                    b.Navigation("Origin");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Role", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("Roles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("roles_project_id_fkey");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.SensitivityLabel", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Organization", "Organization")
                        .WithMany("SensitivityLabels")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sensitivity_labels_organization_id_fkey");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Subscription", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Action", "Action")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("subscriptions_action_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.DataSource", "DataSource")
                        .WithMany("Subscriptions")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("subscriptions_dataSource_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("subscriptions_project_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("subscriptions_user_id_fkey");

                    b.Navigation("Action");

                    b.Navigation("DataSource");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Tag", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("Tags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tags_project_id_fkey");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Action", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Class", b =>
                {
                    b.Navigation("EdgeMappingDestinations");

                    b.Navigation("EdgeMappingOrigins");

                    b.Navigation("RecordMappings");

                    b.Navigation("Records");

                    b.Navigation("RelationshipDestinations");

                    b.Navigation("RelationshipOrigins");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.DataSource", b =>
                {
                    b.Navigation("EdgeMappings");

                    b.Navigation("Edges");

                    b.Navigation("Events");

                    b.Navigation("RecordMappings");

                    b.Navigation("Records");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Edge", b =>
                {
                    b.Navigation("HistoricalEdges");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.EdgeMapping", b =>
                {
                    b.Navigation("Edges");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Group", b =>
                {
                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.ObjectStorage", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Organization", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("OrganizationUsers");

                    b.Navigation("Projects");

                    b.Navigation("SensitivityLabels");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Project", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Classes");

                    b.Navigation("DataSources");

                    b.Navigation("EdgeMappings");

                    b.Navigation("Edges");

                    b.Navigation("Events");

                    b.Navigation("ObjectStorages");

                    b.Navigation("ProjectMembers");

                    b.Navigation("RecordMappings");

                    b.Navigation("Records");

                    b.Navigation("Relationships");

                    b.Navigation("Roles");

                    b.Navigation("Subscriptions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Record", b =>
                {
                    b.Navigation("EdgeDestinations");

                    b.Navigation("EdgeOrigins");

                    b.Navigation("HistoricalRecords");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.RecordMapping", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Relationship", b =>
                {
                    b.Navigation("EdgeMappings");

                    b.Navigation("Edges");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Role", b =>
                {
                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.SensitivityLabel", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.User", b =>
                {
                    b.Navigation("OrganizationUsers");

                    b.Navigation("ProjectMembers");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
