// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using deeplynx.datalayer.Models;

#nullable disable

namespace deeplynx.datalayer.Migrations
{
    [DbContext(typeof(DeeplynxContext))]
    [Migration("20250417171646_001_InitialCreation-041725")]
    partial class _001_InitialCreation041725
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserProject", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.HasKey("UserId", "ProjectId")
                        .HasName("user_projects_pkey");

                    b.HasIndex("ProjectId");

                    b.ToTable("user_projects", "deeplynx");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("RoleId", "UserId")
                        .HasName("user_roles_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("user_roles", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Class", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Uuid")
                        .HasColumnType("text")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("classes_pkey");

                    b.HasIndex("ProjectId");

                    b.ToTable("classes", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.DataSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<string>("BaseUri")
                        .HasColumnType("text")
                        .HasColumnName("base_uri");

                    b.Property<string>("Config")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("data_sources_pkey");

                    b.HasIndex("ProjectId");

                    b.ToTable("data_sources", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Edge", b =>
                {
                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_id");

                    b.Property<long>("DestinationId")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_id");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<long?>("RelationshipId")
                        .HasColumnType("bigint")
                        .HasColumnName("relationship_id");

                    b.Property<string>("RelationshipName")
                        .HasColumnType("text")
                        .HasColumnName("relationship_name");

                    b.HasKey("OriginId", "DestinationId")
                        .HasName("edges_pkey");

                    b.HasIndex("DestinationId");

                    b.HasIndex("RelationshipId");

                    b.ToTable("edges", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.EdgeParameter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("DestinationId")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_id");

                    b.Property<string>("DestinationParams")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("destination_params");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_id");

                    b.Property<string>("OriginParams")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("origin_params");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long>("RelationshipId")
                        .HasColumnType("bigint")
                        .HasColumnName("relationship_id");

                    b.HasKey("Id")
                        .HasName("edge_parameters_pkey");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RelationshipId");

                    b.ToTable("edge_parameters", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessType")
                        .HasColumnType("text")
                        .HasColumnName("access_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long?>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<long?>("RecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("record_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("permissions_pkey");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("RecordId");

                    b.HasIndex("RoleId");

                    b.ToTable("permissions", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("projects_pkey");

                    b.ToTable("projects", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Record", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<string>("ClassName")
                        .HasColumnType("text")
                        .HasColumnName("class_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomId")
                        .HasColumnType("text")
                        .HasColumnName("custom_id");

                    b.Property<long>("DataSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("data_source_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OriginalId")
                        .HasColumnType("text")
                        .HasColumnName("original_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("Uri")
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("records_pkey");

                    b.HasIndex("ClassId");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("ProjectId");

                    b.ToTable("records", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.RecordParameter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("RecordParams")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("record_params");

                    b.HasKey("Id")
                        .HasName("record_parameters_pkey");

                    b.HasIndex("ClassId");

                    b.ToTable("record_parameters", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Relationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DestinationId")
                        .HasColumnType("bigint")
                        .HasColumnName("destination_id");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Uuid")
                        .HasColumnType("text")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("relationships_pkey");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.HasIndex("ProjectId");

                    b.ToTable("relationships", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex("ProjectId");

                    b.ToTable("roles", "deeplynx");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", "deeplynx");
                });

            modelBuilder.Entity("UserProject", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_projects_project_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_projects_user_id_fkey");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_role_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_user_id_fkey");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Class", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("Classes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("classes_project_id_fkey");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.DataSource", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("DataSources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("data_sources_project_id_fkey");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Edge", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Record", "Destination")
                        .WithMany("EdgeDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edges_destination_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Record", "Origin")
                        .WithMany("EdgeOrigins")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edges_origin_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Relationship", "Relationship")
                        .WithMany("Edges")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("edges_relationship_id_fkey");

                    b.Navigation("Destination");

                    b.Navigation("Origin");

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.EdgeParameter", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Class", "Destination")
                        .WithMany("EdgeParameterDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edge_parameters_destination_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Class", "Origin")
                        .WithMany("EdgeParameterOrigins")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edge_parameters_origin_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("EdgeParameters")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edge_parameters_project_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Relationship", "Relationship")
                        .WithMany("EdgeParameters")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("edge_parameters_relationship_id_fkey");

                    b.Navigation("Destination");

                    b.Navigation("Origin");

                    b.Navigation("Project");

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Permission", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.DataSource", "DataSource")
                        .WithMany("Permissions")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("permissions_data_source_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Record", "Record")
                        .WithMany("Permissions")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("permissions_record_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("permissions_role_id_fkey");

                    b.Navigation("DataSource");

                    b.Navigation("Record");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Record", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Class", "Class")
                        .WithMany("Records")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("records_class_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.DataSource", "DataSource")
                        .WithMany("Records")
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_data_source_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("Records")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("records_project_id_fkey");

                    b.Navigation("Class");

                    b.Navigation("DataSource");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.RecordParameter", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Class", "Class")
                        .WithMany("RecordParameters")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("record_parameters_class_id_fkey");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Relationship", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Class", "Destination")
                        .WithMany("RelationshipDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("relationships_destination_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Class", "Origin")
                        .WithMany("RelationshipOrigins")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("relationships_origin_id_fkey");

                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("Relationships")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("relationships_project_id_fkey");

                    b.Navigation("Destination");

                    b.Navigation("Origin");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Role", b =>
                {
                    b.HasOne("deeplynx.datalayer.Models.Project", "Project")
                        .WithMany("Roles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("roles_project_id_fkey");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Class", b =>
                {
                    b.Navigation("EdgeParameterDestinations");

                    b.Navigation("EdgeParameterOrigins");

                    b.Navigation("RecordParameters");

                    b.Navigation("Records");

                    b.Navigation("RelationshipDestinations");

                    b.Navigation("RelationshipOrigins");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.DataSource", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Records");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Project", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("DataSources");

                    b.Navigation("EdgeParameters");

                    b.Navigation("Records");

                    b.Navigation("Relationships");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Record", b =>
                {
                    b.Navigation("EdgeDestinations");

                    b.Navigation("EdgeOrigins");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Relationship", b =>
                {
                    b.Navigation("EdgeParameters");

                    b.Navigation("Edges");
                });

            modelBuilder.Entity("deeplynx.datalayer.Models.Role", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
