using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace deeplynx.datalayer.Migrations
{
    /// <inheritdoc />
    public partial class SetGeneratedAlways : Migration
    {
        /// <inheritdoc />
       protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE deeplynx.classes ALTER COLUMN id SET GENERATED ALWAYS;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.data_sources ALTER COLUMN id SET GENERATED ALWAYS;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.edge_mappings ALTER COLUMN id SET GENERATED ALWAYS;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.edges ALTER COLUMN id SET GENERATED ALWAYS;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.historical_edges ALTER COLUMN id SET GENERATED ALWAYS;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.historical_records ALTER COLUMN id SET GENERATED ALWAYS;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.projects ALTER COLUMN id SET GENERATED ALWAYS;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.record_mappings ALTER COLUMN id SET GENERATED ALWAYS;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.records ALTER COLUMN id SET GENERATED ALWAYS;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.relationships ALTER COLUMN id SET GENERATED ALWAYS;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.tags ALTER COLUMN id SET GENERATED ALWAYS;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.users ALTER COLUMN id SET GENERATED ALWAYS;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE deeplynx.classes ALTER COLUMN id SET GENERATED BY DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.data_sources ALTER COLUMN id SET GENERATED BY DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.edge_mappings ALTER COLUMN id SET GENERATED BY DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.edges ALTER COLUMN id SET GENERATED BY DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.historical_edges ALTER COLUMN id SET GENERATED BY DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.historical_records ALTER COLUMN id SET GENERATED BY DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.projects ALTER COLUMN id SET GENERATED BY DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.record_mappings ALTER COLUMN id SET GENERATED BY DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.records ALTER COLUMN id SET GENERATED BY DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.relationships ALTER COLUMN id SET GENERATED BY DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.tags ALTER COLUMN id SET GENERATED BY DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE deeplynx.users ALTER COLUMN id SET GENERATED BY DEFAULT;");
        }
    }
}
