services:
  ui:
    build:
      context: ./
      dockerfile: Dockerfiles/ui/Dockerfile.local
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:5000/api"
        NEXT_PUBLIC_DOCS_PATH: "http://docs:3000"
    environment:
      NODE_ENV: production
      BACKEND_BASE_URL: "http://server:5000/api"
      NEXT_PUBLIC_DOCS_PATH: "http://localhost:3001"
    ports:
      - "3000:3000"
    networks:
      - nexus-network
    depends_on:
      - server

  docs:
    build:
      context: ./
      dockerfile: Dockerfiles/docs/Dockerfile.local
    environment:
      NODE_ENV: production
    ports:
      - "3001:3001"
    networks:
      - nexus-network
    depends_on:
      - server

  server:
    build:
      context: ./
      dockerfile: Dockerfiles/server/Dockerfile.local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nexuscore
      POSTGRES_DB_NAME: deeplynx
      POSTGRES_DB_HOST: nx-postgres
      POSTGRES_PORT: 5432
      FILE_STORAGE_METHOD: filesystem # values can be filesystem, azure_object, and aws_s3
      STORAGE_DIRECTORY: /data
      AZURE_OBJECT_CONNECTION_STRING: azure-example-connection-string
      AWS_S3_CONNECTION_STRING: aws-example-connection-string
      # this is under development, ask about getting scalar working for the docker server
      ScalarApi__BaseUrl: http://scalar-api:5050 # http://localhost:5000/scalar/, not 5050.
      SMTP_SERVER: mailhost.inl.gov
      SMTP_PORT: 25
      SMTP_ENABLE_SSL: false
      FROM_EMAIL: no-reply@inl.gov
      FROM_NAME: DeepLynx Nexus
      INVITE_URL: http://localhost:3000
      SUPPORT_EMAIL: jaren.brownlee@inl.gov
      DISABLE_FRONTEND_AUTHENTICATION: false

    entrypoint: /usr/local/bin/entrypoint.sh
    ports:
      - "5000:5000"
    networks:
      - nexus-network
    volumes:
      - object_storage:/data
    depends_on:
        - nx-postgres

  nx-postgres:
    build:
      context: ./
      dockerfile: Dockerfiles/database/Dockerfile.local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nexuscore
    ports:
      - "5432"
    networks:
      - nexus-network
    volumes:
      - nx_postgres_data:/var/lib/postgresql/data
    
networks:
  nexus-network:
    driver: bridge
  
volumes:
  object_storage:
    driver: local
  nx_postgres_data:
    driver: local