services:
  ui:
    build:
      context: ./
      dockerfile: Dockerfiles/ui/Dockerfile.local
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_OKTA_CLIENT_ID: ${NEXT_PUBLIC_OKTA_CLIENT_ID}
      NEXT_PUBLIC_OKTA_ISSUER: ${NEXT_PUBLIC_OKTA_ISSUER}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    networks:
      - nexus-network
    depends_on:
      - nx-postgres

  server:
    build:
      context: ./
      dockerfile: Dockerfiles/server/Dockerfile.local
    env_file:
      - .env
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_OKTA_CLIENT_ID: ${NEXT_PUBLIC_OKTA_CLIENT_ID}
      NEXT_PUBLIC_OKTA_ISSUER: ${NEXT_PUBLIC_OKTA_ISSUER}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    entrypoint: /usr/local/bin/entrypoint.sh
    ports:
      - "5000:5000"
    networks:
      - nexus-network
    depends_on:
        - nx-postgres

  nx-postgres:
    build:
      context: ./database
      dockerfile: Dockerfiles/Dockerfile.db.local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nexuscore
    ports:
      - "5432"
    networks:
      - nexus-network
    volumes:
      - nx-postgres-data:/var/lib/postgresql/data
    
networks:
  nexus-network:
    driver: bridge
  
volumes:
  nx-postgres-data:
    driver: local