services:
  ui:
    build:
      context: ./
      dockerfile: Dockerfiles/ui/Dockerfile.local
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:5000/api"
    environment:
      NODE_ENV: production
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_CLIENT_SECRET: ${OKTA_CLIENT_SECRET}
      OKTA_ISSUER: ${OKTA_ISSUER}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      BACKEND_BASE_URL: "http://server:5000/api"
    ports:
      - "3000:3000"
    networks:
      - nexus-network
    depends_on:
      - server

  server:
    build:
      context: ./
      dockerfile: Dockerfiles/server/Dockerfile.local
    env_file:
      - .env
    environment:
      NODE_ENV: production
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_ISSUER: ${OKTA_ISSUER}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    entrypoint: /usr/local/bin/entrypoint.sh
    ports:
      - "5000:5000"
    networks:
      - nexus-network
    depends_on:
        - nx-postgres

  nx-postgres:
    build:
      context: ./
      dockerfile: Dockerfiles/database/Dockerfile.local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nexuscore
    ports:
      - "5432"
    networks:
      - nexus-network
    volumes:
      - nx-postgres-data:/var/lib/postgresql/data
    
networks:
  nexus-network:
    driver: bridge
  
volumes:
  nx-postgres-data:
    driver: local