 /* Dummy Data */
export const initialTableData = [
  {
    name: "Alexis Wiley",
    country: "Canada",
    adapterType: "Standard",
    active: true,
    id: "5623",
  },
  {
    name: "Jordan Smith",
    country: "Germany",
    adapterType: "TimeSeries",
    active: false,
    id: "8712",
  },
  {
    name: "Taylor Brown",
    country: "Australia",
    adapterType: "Standard",
    active: true,
    id: "3490",
  },
  {
    name: "Morgan Lee",
    country: "Japan",
    adapterType: "Standard",
    active: false,
    id: "2201",
  },
  {
    name: "Casey Green",
    country: "Brazil",
    adapterType: "TimeSeries",
    active: true,
    id: "4537",
  },
  {
    name: "Dakota Johnson",
    country: "France",
    adapterType: "Standard",
    active: false,
    id: "6345",
  },
  {
    name: "Riley Cooper",
    country: "India",
    adapterType: "TimeSeries",
    active: true,
    id: "7889",
  },
  {
    name: "Quinn Parker",
    country: "Italy",
    adapterType: "Standard",
    active: false,
    id: "9123",
  },
  {
    name: "Avery Morgan",
    country: "South Africa",
    adapterType: "TimeSeries",
    active: true,
    id: "1045",
  },
  {
    name: "Payton Brooks",
    country: "South Korea",
    adapterType: "Standard",
    active: true,
    id: "5567",
  },
  {
    name: "Charlie Taylor",
    country: "Mexico",
    adapterType: "TimeSeries",
    active: false,
    id: "6691",
  },
  {
    name: "Skyler Adams",
    country: "Spain",
    adapterType: "Standard",
    active: true,
    id: "7823",
  },
  {
    name: "Jamie Kelly",
    country: "Netherlands",
    adapterType: "TimeSeries",
    active: false,
    id: "8934",
  },
  {
    name: "Kendall Reed",
    country: "New Zealand",
    adapterType: "Standard",
    active: true,
    id: "9045",
  },
  {
    name: "Hayden Walker",
    country: "Sweden",
    adapterType: "TimeSeries",
    active: true,
    id: "2156",
  },
  {
    name: "Jordan Murphy",
    country: "Norway",
    adapterType: "Standard",
    active: false,
    id: "3267",
  },
  {
    name: "Casey Bailey",
    country: "Denmark",
    adapterType: "TimeSeries",
    active: true,
    id: "4378",
  },
  {
    name: "Morgan Campbell",
    country: "Finland",
    adapterType: "Standard",
    active: true,
    id: "5489",
  },
  {
    name: "Emerson Turner",
    country: "Argentina",
    adapterType: "TimeSeries",
    active: false,
    id: "6590",
  },
  {
    name: "Reagan Brooks",
    country: "Russia",
    adapterType: "Standard",
    active: true,
    id: "7601",
  },
  {
    name: "Parker James",
    country: "China",
    adapterType: "TimeSeries",
    active: true,
    id: "8712",
  },
  {
    name: "Jordan Kelly",
    country: "Thailand",
    adapterType: "Standard",
    active: false,
    id: "9823",
  },
  {
    name: "Blake Morgan",
    country: "Chile",
    adapterType: "TimeSeries",
    active: true,
    id: "1034",
  },
  {
    name: "Drew Parker",
    country: "Malaysia",
    adapterType: "Standard",
    active: true,
    id: "2145",
  },
  {
    name: "Jordan Walker",
    country: "Vietnam",
    adapterType: "TimeSeries",
    active: false,
    id: "3256",
  },
  {
    name: "Taylor Campbell",
    country: "Greece",
    adapterType: "Standard",
    active: true,
    id: "4367",
  },
  {
    name: "Morgan Brown",
    country: "Turkey",
    adapterType: "TimeSeries",
    active: true,
    id: "5478",
  },
  {
    name: "Alexis Cooper",
    country: "Switzerland",
    adapterType: "Standard",
    active: false,
    id: "6589",
  },
  {
    name: "Jordan Reed",
    country: "Austria",
    adapterType: "TimeSeries",
    active: true,
    id: "7690",
  },
  {
    name: "Hayden Adams",
    country: "Belgium",
    adapterType: "Standard",
    active: true,
    id: "8701",
  },
  {
    name: "Casey Murphy",
    country: "Portugal",
    adapterType: "TimeSeries",
    active: false,
    id: "9812",
  },
  {
    name: "Taylor Johnson",
    country: "Poland",
    adapterType: "Standard",
    active: true,
    id: "1923",
  },
  {
    name: "Riley Green",
    country: "Czech Republic",
    adapterType: "TimeSeries",
    active: true,
    id: "2034",
  },
  {
    name: "Jordan Lee",
    country: "Ireland",
    adapterType: "Standard",
    active: false,
    id: "3145",
  },
  {
    name: "Dakota Bailey",
    country: "Hungary",
    adapterType: "TimeSeries",
    active: true,
    id: "4256",
  },
  {
    name: "Skyler Murphy",
    country: "Romania",
    adapterType: "Standard",
    active: true,
    id: "5367",
  },
  {
    name: "Jamie Walker",
    country: "Bulgaria",
    adapterType: "TimeSeries",
    active: false,
    id: "6478",
  },
  {
    name: "Casey Adams",
    country: "Slovakia",
    adapterType: "Standard",
    active: true,
    id: "7589",
  },
  {
    name: "Morgan Smith",
    country: "Croatia",
    adapterType: "TimeSeries",
    active: true,
    id: "8690",
  },
  {
    name: "Taylor James",
    country: "Lithuania",
    adapterType: "Standard",
    active: false,
    id: "9701",
  },
  {
    name: "Jordan Reed",
    country: "Estonia",
    adapterType: "TimeSeries",
    active: true,
    id: "1081",
  },
  {
    name: "Alexis Johnson",
    country: "Latvia",
    adapterType: "Standard",
    active: true,
    id: "2192",
  },
  {
    name: "Riley Cooper",
    country: "Slovenia",
    adapterType: "TimeSeries",
    active: false,
    id: "3203",
  },
  {
    name: "Jamie Lee",
    country: "Cyprus",
    adapterType: "Standard",
    active: true,
    id: "4314",
  },
  {
    name: "Taylor Brown",
    country: "Luxembourg",
    adapterType: "TimeSeries",
    active: true,
    id: "5425",
  },
  {
    name: "Casey Green",
    country: "Malta",
    adapterType: "Standard",
    active: false,
    id: "6536",
  },
  {
    name: "Morgan Parker",
    country: "Iceland",
    adapterType: "TimeSeries",
    active: true,
    id: "7647",
  },
  {
    name: "Jordan Adams",
    country: "Monaco",
    adapterType: "Standard",
    active: true,
    id: "8758",
  },
  {
    name: "Hayden Walker",
    country: "Liechtenstein",
    adapterType: "TimeSeries",
    active: false,
    id: "9869",
  },
  {
    name: "Skyler Taylor",
    country: "San Marino",
    adapterType: "Standard",
    active: true,
    id: "1970",
  },
  {
    name: "Dakota Murphy",
    country: "Andorra",
    adapterType: "TimeSeries",
    active: true,
    id: "2081",
  },
  {
    name: "Jamie Johnson",
    country: "Vatican City",
    adapterType: "Standard",
    active: false,
    id: "3192",
  },
  {
    name: "Quinn Kelly",
    country: "Singapore",
    adapterType: "TimeSeries",
    active: true,
    id: "4303",
  },
  {
    name: "Peyton Lee",
    country: "Malaysia",
    adapterType: "Standard",
    active: false,
    id: "5414",
  },
  {
    name: "Blake Parker",
    country: "Philippines",
    adapterType: "TimeSeries",
    active: true,
    id: "6525",
  },
  {
    name: "Drew Smith",
    country: "Indonesia",
    adapterType: "Standard",
    active: true,
    id: "7636",
  },
  {
    name: "Jordan Green",
    country: "Thailand",
    adapterType: "TimeSeries",
    active: false,
    id: "8747",
  },
  {
    name: "Riley Johnson",
    country: "Vietnam",
    adapterType: "Standard",
    active: true,
    id: "9858",
  },
  {
    name: "Casey Walker",
    country: "Myanmar",
    adapterType: "TimeSeries",
    active: true,
    id: "1969",
  },
  {
    name: "Morgan Taylor",
    country: "Cambodia",
    adapterType: "Standard",
    active: false,
    id: "2070",
  },
  {
    name: "Taylor Reed",
    country: "Laos",
    adapterType: "TimeSeries",
    active: true,
    id: "3181",
  },
  {
    name: "Jordan Cooper",
    country: "Sri Lanka",
    adapterType: "Standard",
    active: true,
    id: "4292",
  },
  {
    name: "Hayden Campbell",
    country: "Nepal",
    adapterType: "TimeSeries",
    active: false,
    id: "5403",
  },
  {
    name: "Skyler Murphy",
    country: "Bhutan",
    adapterType: "Standard",
    active: true,
    id: "6514",
  },
  {
    name: "Jamie Adams",
    country: "Maldives",
    adapterType: "TimeSeries",
    active: true,
    id: "7625",
  },
  {
    name: "Casey Johnson",
    country: "Brunei",
    adapterType: "Standard",
    active: false,
    id: "8736",
  },
  {
    name: "Morgan Brown",
    country: "Timor-Leste",
    adapterType: "TimeSeries",
    active: true,
    id: "9847",
  },
  {
    name: "Taylor Smith",
    country: "Papua New Guinea",
    adapterType: "Standard",
    active: true,
    id: "1958",
  },
  {
    name: "Jordan Green",
    country: "Fiji",
    adapterType: "TimeSeries",
    active: false,
    id: "2069",
  },
  {
    name: "Alexis Lee",
    country: "Solomon Islands",
    adapterType: "Standard",
    active: true,
    id: "3170",
  },
  {
    name: "Riley Parker",
    country: "Vanuatu",
    adapterType: "TimeSeries",
    active: true,
    id: "4281",
  },
  {
    name: "Jamie Walker",
    country: "Kiribati",
    adapterType: "Standard",
    active: false,
    id: "5392",
  },
  {
    name: "Taylor Adams",
    country: "Tonga",
    adapterType: "TimeSeries",
    active: true,
    id: "6503",
  },
  {
    name: "Morgan Johnson",
    country: "Micronesia",
    adapterType: "Standard",
    active: true,
    id: "7614",
  },
  {
    name: "Casey Brown",
    country: "Marshall Islands",
    adapterType: "TimeSeries",
    active: false,
    id: "8725",
  },
  {
    name: "Jordan Smith",
    country: "Palau",
    adapterType: "Standard",
    active: true,
    id: "9836",
  },
  {
    name: "Riley Green",
    country: "Nauru",
    adapterType: "TimeSeries",
    active: true,
    id: "1947",
  },
  {
    name: "Hayden Lee",
    country: "Tuvalu",
    adapterType: "Standard",
    active: false,
    id: "2058",
  },
  {
    name: "Skyler Parker",
    country: "Samoa",
    adapterType: "TimeSeries",
    active: true,
    id: "3169",
  },
  {
    name: "Jamie Walker",
    country: "Australia",
    adapterType: "Standard",
    active: true,
    id: "4270",
  },
  {
    name: "Casey Adams",
    country: "New Zealand",
    adapterType: "TimeSeries",
    active: false,
    id: "5381",
  },
  {
    name: "Morgan Johnson",
    country: "Fiji",
    adapterType: "Standard",
    active: true,
    id: "6492",
  }
];

  /* Dummy Data */
export const fileTableData = [
    {
      id: 1,
      fileName: "datafile1.csv",
      timeseries: true,
      fileSize: 124,
      dateModified: "2025-04-01",
      select: false,
    },
    {
      id: 2,
      fileName: "datafile2.csv",
      timeseries: true,
      fileSize: 98,
      dateModified: "2025-04-02",
      select: false,
    },
    {
      id: 3,
      fileName: "datafile3.csv",
      timeseries: false,
      fileSize: 112,
      dateModified: "2025-04-03",
      select: false,
    },
    {
      id: 4,
      fileName: "datafile4.csv",
      timeseries: true,
      fileSize: 145,
      dateModified: "2025-04-04",
      select: false,
    },
    {
      id: 5,
      fileName: "datafile5.csv",
      timeseries: false,
      fileSize: 87,
      dateModified: "2025-04-05",
      select: false,
    },
    {
      id: 6,
      fileName: "datafile6.csv",
      timeseries: false,
      fileSize: 130,
      dateModified: "2025-04-06",
      select: false,
    },
    {
      id: 7,
      fileName: "datafile7.csv",
      timeseries: false,
      fileSize: 154,
      dateModified: "2025-04-07",
      select: false,
    },
    {
      id: 8,
      fileName: "datafile8.csv",
      timeseries: true,
      fileSize: 102,
      dateModified: "2025-04-08",
      select: false,
    },
    {
      id: 9,
      fileName: "datafile9.csv",
      timeseries: true,
      fileSize: 121,
      dateModified: "2025-04-09",
      select: false,
    },
    {
      id: 10,
      fileName: "datafile10.csv",
      timeseries: true,
      fileSize: 110,
      dateModified: "2025-04-10",
      select: false,
    },
    {
      id: 1,
      fileName: "datafile1.csv",
      timeseries: true,
      fileSize: 124,
      dateModified: "2025-04-01",
      select: false,
    },
    {
      id: 2,
      fileName: "datafile2.csv",
      timeseries: true,
      fileSize: 98,
      dateModified: "2025-04-02",
      select: false,
    },
    {
      id: 3,
      fileName: "datafile3.csv",
      timeseries: false,
      fileSize: 112,
      dateModified: "2025-04-03",
      select: false,
    },
    {
      id: 4,
      fileName: "datafile4.csv",
      timeseries: true,
      fileSize: 145,
      dateModified: "2025-04-04",
      select: false,
    },
    {
      id: 5,
      fileName: "datafile5.csv",
      timeseries: false,
      fileSize: 87,
      dateModified: "2025-04-05",
      select: false,
    },
    {
      id: 6,
      fileName: "datafile6.csv",
      timeseries: false,
      fileSize: 130,
      dateModified: "2025-04-06",
      select: false,
    },
    {
      id: 7,
      fileName: "datafile7.csv",
      timeseries: false,
      fileSize: 154,
      dateModified: "2025-04-07",
      select: false,
    },
    {
      id: 8,
      fileName: "datafile8.csv",
      timeseries: true,
      fileSize: 102,
      dateModified: "2025-04-08",
      select: false,
    },
    {
      id: 9,
      fileName: "datafile9.csv",
      timeseries: true,
      fileSize: 121,
      dateModified: "2025-04-09",
      select: false,
    },
    {
      id: 10,
      fileName: "datafile10.csv",
      timeseries: true,
      fileSize: 110,
      dateModified: "2025-04-10",
      select: false,
    },
  ];