 /* Dummy Data */
export const initialTableData = [
  {
    name: "Alexis Wiley",
    country: "Canada",
    adapterType: "Standard",
    active: true,
    id: "5623",
  },
  {
    name: "Jordan Smith",
    country: "Germany",
    adapterType: "TimeSeries",
    active: false,
    id: "8712",
  },
  {
    name: "Taylor Brown",
    country: "Australia",
    adapterType: "Standard",
    active: true,
    id: "3490",
  },
  {
    name: "Morgan Lee",
    country: "Japan",
    adapterType: "Standard",
    active: false,
    id: "2201",
  },
  {
    name: "Casey Green",
    country: "Brazil",
    adapterType: "TimeSeries",
    active: true,
    id: "4537",
  },
  {
    name: "Dakota Johnson",
    country: "France",
    adapterType: "Standard",
    active: false,
    id: "6345",
  },
  {
    name: "Riley Cooper",
    country: "India",
    adapterType: "TimeSeries",
    active: true,
    id: "7889",
  },
  {
    name: "Quinn Parker",
    country: "Italy",
    adapterType: "Standard",
    active: false,
    id: "9123",
  },
  {
    name: "Avery Morgan",
    country: "South Africa",
    adapterType: "TimeSeries",
    active: true,
    id: "1045",
  },
  {
    name: "Payton Brooks",
    country: "South Korea",
    adapterType: "Standard",
    active: true,
    id: "5567",
  },
  {
    name: "Charlie Taylor",
    country: "Mexico",
    adapterType: "TimeSeries",
    active: false,
    id: "6691",
  },
  {
    name: "Skyler Adams",
    country: "Spain",
    adapterType: "Standard",
    active: true,
    id: "7823",
  },
  {
    name: "Jamie Kelly",
    country: "Netherlands",
    adapterType: "TimeSeries",
    active: false,
    id: "8934",
  },
  {
    name: "Kendall Reed",
    country: "New Zealand",
    adapterType: "Standard",
    active: true,
    id: "9045",
  },
  {
    name: "Hayden Walker",
    country: "Sweden",
    adapterType: "TimeSeries",
    active: true,
    id: "2156",
  },
  {
    name: "Jordan Murphy",
    country: "Norway",
    adapterType: "Standard",
    active: false,
    id: "3267",
  },
  {
    name: "Casey Bailey",
    country: "Denmark",
    adapterType: "TimeSeries",
    active: true,
    id: "4378",
  },
  {
    name: "Morgan Campbell",
    country: "Finland",
    adapterType: "Standard",
    active: true,
    id: "5489",
  },
  {
    name: "Emerson Turner",
    country: "Argentina",
    adapterType: "TimeSeries",
    active: false,
    id: "6590",
  },
  {
    name: "Reagan Brooks",
    country: "Russia",
    adapterType: "Standard",
    active: true,
    id: "7601",
  },
  {
    name: "Parker James",
    country: "China",
    adapterType: "TimeSeries",
    active: true,
    id: "8712",
  },
  {
    name: "Jordan Kelly",
    country: "Thailand",
    adapterType: "Standard",
    active: false,
    id: "9823",
  },
  {
    name: "Blake Morgan",
    country: "Chile",
    adapterType: "TimeSeries",
    active: true,
    id: "1034",
  },
  {
    name: "Drew Parker",
    country: "Malaysia",
    adapterType: "Standard",
    active: true,
    id: "2145",
  },
  {
    name: "Jordan Walker",
    country: "Vietnam",
    adapterType: "TimeSeries",
    active: false,
    id: "3256",
  },
  {
    name: "Taylor Campbell",
    country: "Greece",
    adapterType: "Standard",
    active: true,
    id: "4367",
  },
  {
    name: "Morgan Brown",
    country: "Turkey",
    adapterType: "TimeSeries",
    active: true,
    id: "5478",
  },
  {
    name: "Alexis Cooper",
    country: "Switzerland",
    adapterType: "Standard",
    active: false,
    id: "6589",
  },
  {
    name: "Jordan Reed",
    country: "Austria",
    adapterType: "TimeSeries",
    active: true,
    id: "7690",
  },
  {
    name: "Hayden Adams",
    country: "Belgium",
    adapterType: "Standard",
    active: true,
    id: "8701",
  },
  {
    name: "Casey Murphy",
    country: "Portugal",
    adapterType: "TimeSeries",
    active: false,
    id: "9812",
  },
  {
    name: "Taylor Johnson",
    country: "Poland",
    adapterType: "Standard",
    active: true,
    id: "1923",
  },
  {
    name: "Riley Green",
    country: "Czech Republic",
    adapterType: "TimeSeries",
    active: true,
    id: "2034",
  },
  {
    name: "Jordan Lee",
    country: "Ireland",
    adapterType: "Standard",
    active: false,
    id: "3145",
  },
  {
    name: "Dakota Bailey",
    country: "Hungary",
    adapterType: "TimeSeries",
    active: true,
    id: "4256",
  },
  {
    name: "Skyler Murphy",
    country: "Romania",
    adapterType: "Standard",
    active: true,
    id: "5367",
  },
  {
    name: "Jamie Walker",
    country: "Bulgaria",
    adapterType: "TimeSeries",
    active: false,
    id: "6478",
  },
  {
    name: "Casey Adams",
    country: "Slovakia",
    adapterType: "Standard",
    active: true,
    id: "7589",
  },
  {
    name: "Morgan Smith",
    country: "Croatia",
    adapterType: "TimeSeries",
    active: true,
    id: "8690",
  },
  {
    name: "Taylor James",
    country: "Lithuania",
    adapterType: "Standard",
    active: false,
    id: "9701",
  },
  {
    name: "Jordan Reed",
    country: "Estonia",
    adapterType: "TimeSeries",
    active: true,
    id: "1081",
  },
  {
    name: "Alexis Johnson",
    country: "Latvia",
    adapterType: "Standard",
    active: true,
    id: "2192",
  },
  {
    name: "Riley Cooper",
    country: "Slovenia",
    adapterType: "TimeSeries",
    active: false,
    id: "3203",
  },
  {
    name: "Jamie Lee",
    country: "Cyprus",
    adapterType: "Standard",
    active: true,
    id: "4314",
  },
  {
    name: "Taylor Brown",
    country: "Luxembourg",
    adapterType: "TimeSeries",
    active: true,
    id: "5425",
  },
  {
    name: "Casey Green",
    country: "Malta",
    adapterType: "Standard",
    active: false,
    id: "6536",
  },
  {
    name: "Morgan Parker",
    country: "Iceland",
    adapterType: "TimeSeries",
    active: true,
    id: "7647",
  },
  {
    name: "Jordan Adams",
    country: "Monaco",
    adapterType: "Standard",
    active: true,
    id: "8758",
  },
  {
    name: "Hayden Walker",
    country: "Liechtenstein",
    adapterType: "TimeSeries",
    active: false,
    id: "9869",
  },
  {
    name: "Skyler Taylor",
    country: "San Marino",
    adapterType: "Standard",
    active: true,
    id: "1970",
  },
  {
    name: "Dakota Murphy",
    country: "Andorra",
    adapterType: "TimeSeries",
    active: true,
    id: "2081",
  },
  {
    name: "Jamie Johnson",
    country: "Vatican City",
    adapterType: "Standard",
    active: false,
    id: "3192",
  },
  {
    name: "Quinn Kelly",
    country: "Singapore",
    adapterType: "TimeSeries",
    active: true,
    id: "4303",
  },
  {
    name: "Peyton Lee",
    country: "Malaysia",
    adapterType: "Standard",
    active: false,
    id: "5414",
  },
  {
    name: "Blake Parker",
    country: "Philippines",
    adapterType: "TimeSeries",
    active: true,
    id: "6525",
  },
  {
    name: "Drew Smith",
    country: "Indonesia",
    adapterType: "Standard",
    active: true,
    id: "7636",
  },
  {
    name: "Jordan Green",
    country: "Thailand",
    adapterType: "TimeSeries",
    active: false,
    id: "8747",
  },
  {
    name: "Riley Johnson",
    country: "Vietnam",
    adapterType: "Standard",
    active: true,
    id: "9858",
  },
  {
    name: "Casey Walker",
    country: "Myanmar",
    adapterType: "TimeSeries",
    active: true,
    id: "1969",
  },
  {
    name: "Morgan Taylor",
    country: "Cambodia",
    adapterType: "Standard",
    active: false,
    id: "2070",
  },
  {
    name: "Taylor Reed",
    country: "Laos",
    adapterType: "TimeSeries",
    active: true,
    id: "3181",
  },
  {
    name: "Jordan Cooper",
    country: "Sri Lanka",
    adapterType: "Standard",
    active: true,
    id: "4292",
  },
  {
    name: "Hayden Campbell",
    country: "Nepal",
    adapterType: "TimeSeries",
    active: false,
    id: "5403",
  },
  {
    name: "Skyler Murphy",
    country: "Bhutan",
    adapterType: "Standard",
    active: true,
    id: "6514",
  },
  {
    name: "Jamie Adams",
    country: "Maldives",
    adapterType: "TimeSeries",
    active: true,
    id: "7625",
  },
  {
    name: "Casey Johnson",
    country: "Brunei",
    adapterType: "Standard",
    active: false,
    id: "8736",
  },
  {
    name: "Morgan Brown",
    country: "Timor-Leste",
    adapterType: "TimeSeries",
    active: true,
    id: "9847",
  },
  {
    name: "Taylor Smith",
    country: "Papua New Guinea",
    adapterType: "Standard",
    active: true,
    id: "1958",
  },
  {
    name: "Jordan Green",
    country: "Fiji",
    adapterType: "TimeSeries",
    active: false,
    id: "2069",
  },
  {
    name: "Alexis Lee",
    country: "Solomon Islands",
    adapterType: "Standard",
    active: true,
    id: "3170",
  },
  {
    name: "Riley Parker",
    country: "Vanuatu",
    adapterType: "TimeSeries",
    active: true,
    id: "4281",
  },
  {
    name: "Jamie Walker",
    country: "Kiribati",
    adapterType: "Standard",
    active: false,
    id: "5392",
  },
  {
    name: "Taylor Adams",
    country: "Tonga",
    adapterType: "TimeSeries",
    active: true,
    id: "6503",
  },
  {
    name: "Morgan Johnson",
    country: "Micronesia",
    adapterType: "Standard",
    active: true,
    id: "7614",
  },
  {
    name: "Casey Brown",
    country: "Marshall Islands",
    adapterType: "TimeSeries",
    active: false,
    id: "8725",
  },
  {
    name: "Jordan Smith",
    country: "Palau",
    adapterType: "Standard",
    active: true,
    id: "9836",
  },
  {
    name: "Riley Green",
    country: "Nauru",
    adapterType: "TimeSeries",
    active: true,
    id: "1947",
  },
  {
    name: "Hayden Lee",
    country: "Tuvalu",
    adapterType: "Standard",
    active: false,
    id: "2058",
  },
  {
    name: "Skyler Parker",
    country: "Samoa",
    adapterType: "TimeSeries",
    active: true,
    id: "3169",
  },
  {
    name: "Jamie Walker",
    country: "Australia",
    adapterType: "Standard",
    active: true,
    id: "4270",
  },
  {
    name: "Casey Adams",
    country: "New Zealand",
    adapterType: "TimeSeries",
    active: false,
    id: "5381",
  },
  {
    name: "Morgan Johnson",
    country: "Fiji",
    adapterType: "Standard",
    active: true,
    id: "6492",
  }
];

  /* Dummy Data */
  export const fileTableData = [
    {
      id: 1,
      fileName: "weather_data.csv",
      fileDescription: "Contains historical weather data including temperature, precipitation, and wind speed.",
      fileType: "CSV",
      timeseries: true,
      fileSize: 124,
      dateModified: "2025-04-01",
      select: false,
      tags: ["Climate", "Temperature", "Precipitation"],
      lastEdit: "2025-05-15",
    },
    {
      id: 2,
      fileName: "sales_report.pdf",
      fileDescription: "Monthly sales report for the retail division, including revenue and units sold.",
      fileType: "PDF",
      timeseries: true,
      fileSize: 98,
      dateModified: "2025-04-02",
      select: false,
      tags: ["Finance", "Retail", "Monthly Report"],
      lastEdit: "2025-05-12",
    },
    {
      id: 3,
      fileName: "employee_records.xlsx",
      fileDescription: "Details of all employees including personal information and employment history.",
      fileType: "Excel",
      timeseries: false,
      fileSize: 112,
      dateModified: "2025-04-03",
      select: false,
      tags: ["HR", "Employee Data"],
      lastEdit: "2025-05-10",
    },
    {
      id: 4,
      fileName: "inventory_list.csv",
      fileDescription: "List of all inventory items with quantities and storage locations.",
      fileType: "CSV",
      timeseries: true,
      fileSize: 145,
      dateModified: "2025-04-04",
      select: false,
      tags: ["Inventory", "Stock", "Warehouse"],
      lastEdit: "2025-05-08",
    },
    {
      id: 5,
      fileName: "project_timeline.docx",
      fileDescription: "Timeline of the current projects with key milestones and deadlines.",
      fileType: "Word Document",
      timeseries: false,
      fileSize: 87,
      dateModified: "2025-04-05",
      select: false,
      tags: ["Project Management", "Timeline", "Milestones"],
      lastEdit: "2025-05-18",
    },
    {
      id: 6,
      fileName: "customer_feedback.txt",
      fileDescription: "Customer feedback and ratings collected from various surveys.",
      fileType: "Text File",
      timeseries: false,
      fileSize: 130,
      dateModified: "2025-04-06",
      select: false,
      tags: ["Customer Feedback", "Surveys", "Ratings"],
      lastEdit: "2025-05-20",
    },
    {
      id: 7,
      fileName: "financial_summary.pdf",
      fileDescription: "Quarterly financial summary including income statement and balance sheet.",
      fileType: "PDF",
      timeseries: false,
      fileSize: 154,
      dateModified: "2025-04-07",
      select: false,
      tags: ["Finance", "Quarterly Report", "Income Statement", "Balance Sheet"],
      lastEdit: "2025-05-22",
    },
    {
      id: 8,
      fileName: "marketing_analysis.pptx",
      fileDescription: "Analysis of recent marketing campaigns and their performance metrics.",
      fileType: "PowerPoint",
      timeseries: true,
      fileSize: 102,
      dateModified: "2025-04-08",
      select: false,
      tags: ["Marketing", "Campaign Analysis", "Performance Metrics"],
      lastEdit: "2025-05-25",
    },
    {
      id: 9,
      fileName: "research_papers.docx",
      fileDescription: "Collection of research papers and articles related to the ongoing projects.",
      fileType: "Word Document",
      timeseries: true,
      fileSize: 121,
      dateModified: "2025-04-09",
      select: false,
      tags: ["Research", "Articles", "Ongoing Projects"],
      lastEdit: "2025-05-17",
    },
    {
      id: 10,
      fileName: "logistics_data.csv",
      fileDescription: "Logistics data including shipping routes, delivery times, and carrier information.",
      fileType: "CSV",
      timeseries: true,
      fileSize: 110,
      dateModified: "2025-04-10",
      select: false,
      tags: ["Logistics", "Shipping Routes", "Delivery Times", "Carrier Information"],
      lastEdit: "2025-05-19",
    },
  ];

  export const fileData = [
    {
      id: 1,
      fileName: "weather_data.csv",
      fileDescription: "Contains historical weather data including temperature, precipitation, and wind speed.",
      fileType: "CSV",
      timeseries: true,
      fileSize: 124,
      dateModified: "2025-04-01",
      select: false,
      tags: ["Climate", "Temperature", "Precipitation"],
      lastEdit: "2025-05-15",
      source: "Tool",
      time: "2025-03-28T09:15:00",
      container: "Aggregated meteorological records from regional sensors and satellites.",
      location: "/data/climate/2025/weather_data.csv",
    },
    {
      id: 2,
      fileName: "sales_report.pdf",
      fileDescription: "Monthly sales report for the retail division, including revenue and units sold.",
      fileType: "PDF",
      timeseries: true,
      fileSize: 98,
      dateModified: "2025-04-02",
      select: false,
      tags: ["Finance", "Retail", "Monthly Report"],
      lastEdit: "2025-05-12",
      source: "Upload",
      time: "2025-03-30T14:42:00",
      container: "Compiled monthly report submitted by the retail analytics department.",
      location: "\\finance_server\\reports\\retail\\2025\\sales_report.pdf",
    },
    {
      id: 3,
      fileName: "employee_records.xlsx",
      fileDescription: "Details of all employees including personal information and employment history.",
      fileType: "Excel",
      timeseries: false,
      fileSize: 112,
      dateModified: "2025-04-03",
      select: false,
      tags: ["HR", "Employee Data"],
      lastEdit: "2025-05-10",
      source: "Upload",
      time: "2025-03-25T08:10:00",
      container: "Centralized HR database export for internal auditing.",
      location: "/internal/hr/employees/employee_records.xlsx",
    },
    {
      id: 4,
      fileName: "inventory_list.csv",
      fileDescription: "List of all inventory items with quantities and storage locations.",
      fileType: "CSV",
      timeseries: true,
      fileSize: 145,
      dateModified: "2025-04-04",
      select: false,
      tags: ["Inventory", "Stock", "Warehouse"],
      lastEdit: "2025-05-08",
      source: "Tool",
      time: "2025-03-31T11:30:00",
      container: "Live sync from warehouse management system tracking current stock levels.",
      location: "/warehouse/db_exports/inventory/inventory_list.csv",
    },
    {
      id: 5,
      fileName: "project_timeline.docx",
      fileDescription: "Timeline of the current projects with key milestones and deadlines.",
      fileType: "Word Document",
      timeseries: false,
      fileSize: 87,
      dateModified: "2025-04-05",
      select: false,
      tags: ["Project Management", "Timeline", "Milestones"],
      lastEdit: "2025-05-18",
      source: "Upload",
      time: "2025-03-26T16:00:00",
      container: "Project coordination document maintained by the PMO.",
      location: "/projects/2025/timelines/project_timeline.docx",
    },
    {
      id: 6,
      fileName: "customer_feedback.txt",
      fileDescription: "Customer feedback and ratings collected from various surveys.",
      fileType: "Text File",
      timeseries: false,
      fileSize: 130,
      dateModified: "2025-04-06",
      select: false,
      tags: ["Customer Feedback", "Surveys", "Ratings"],
      lastEdit: "2025-05-20",
      source: "Tool",
      time: "2025-04-01T10:22:00",
      container: "Real-time ingestion of customer satisfaction scores from online forms.",
      location: "/analytics/feedback/2025/customer_feedback.txt",
    },
    {
      id: 7,
      fileName: "financial_summary.pdf",
      fileDescription: "Quarterly financial summary including income statement and balance sheet.",
      fileType: "PDF",
      timeseries: false,
      fileSize: 154,
      dateModified: "2025-04-07",
      select: false,
      tags: ["Finance", "Quarterly Report", "Income Statement", "Balance Sheet"],
      lastEdit: "2025-05-22",
      source: "Upload",
      time: "2025-03-29T18:45:00",
      container: "Manually submitted finance report compiled by accounting leadership.",
      location: "\\corporate\\finance\\summaries\\Q1_2025\\financial_summary.pdf",
    },
    {
      id: 8,
      fileName: "marketing_analysis.pptx",
      fileDescription: "Analysis of recent marketing campaigns and their performance metrics.",
      fileType: "PowerPoint",
      timeseries: true,
      fileSize: 102,
      dateModified: "2025-04-08",
      select: false,
      tags: ["Marketing", "Campaign Analysis", "Performance Metrics"],
      lastEdit: "2025-05-25",
      source: "Tool",
      time: "2025-04-02T13:37:00",
      container: "Auto-generated report from the marketing analytics dashboard with trend graphs.",
      location: "/dashboards/marketing/campaigns/marketing_analysis.pptx",
    },
    {
      id: 9,
      fileName: "research_papers.docx",
      fileDescription: "Collection of research papers and articles related to the ongoing projects.",
      fileType: "Word Document",
      timeseries: true,
      fileSize: 121,
      dateModified: "2025-04-09",
      select: false,
      tags: ["Research", "Articles", "Ongoing Projects"],
      lastEdit: "2025-05-17",
      source: "Upload",
      time: "2025-03-27T12:05:00",
      container: "Research contributions from external collaborators and internal teams.",
      location: "/rnd/projects/2025/literature/research_papers.docx",
    },
    {
      id: 10,
      fileName: "logistics_data.csv",
      fileDescription: "Logistics data including shipping routes, delivery times, and carrier information.",
      fileType: "CSV",
      timeseries: true,
      fileSize: 110,
      dateModified: "2025-04-10",
      select: false,
      tags: ["Logistics", "Shipping Routes", "Delivery Times", "Carrier Information"],
      lastEdit: "2025-05-19",
      source: "Tool",
      time: "2025-03-29T07:50:00",
      container: "Export from the logistics tracking system for internal delivery metrics analysis.",
      location: "/logistics/shipping/data/2025/logistics_data.csv",
    },
  ];


   /* Added sample data to pass to project detail */
   export const sampleProjectData = [
    {
      name: "Muzak",
      id: "56231",
      description:
        "Here is a short description of this project and the things that you might find inside of it. Max 150 char.",
      lastViewed: "2025-05-25T14:48:00.000Z",
      created: "2024-11-15T09:30:00.000Z"
    },
    {
      name: "Admin",
      id: "87122",
      description:
        "Here is a short description of this project and the things that you might find inside of it. Max 150 char.",
      lastViewed: "2025-05-26T09:30:00.000Z",
      created: "2024-12-05T13:20:00.000Z"
    },
    {
      name: "Library",
      id: "34903",
      description:
        "Here is a short description of this project and the things that you might find inside of it. Max 150 char.",
      lastViewed: "2025-05-25T12:15:00.000Z",
      created: "2024-10-20T08:45:00.000Z"
    },
    {
      name: "Other Project",
      id: "22014",
      description:
        "Here is is a short description of this project and the things that you might find inside of it. Max 150 char.",
      lastViewed: "2025-05-24T11:20:00.000Z",
      created: "2024-09-30T10:10:00.000Z"
    },
    {
      name: "Other Other Project",
      id: "45375",
      description:
        "Here is a short description of this project and the things that you might find inside of it. Max 150 char.",
      lastViewed: "2025-05-27T07:45:00.000Z",
      created: "2024-11-22T11:55:00.000Z"
    },
    {
      name: "Yet Another Project",
      id: "63456",
      description:
        "Here is a short description of this project and the things that you might find inside of it. Max 150 char.",
      lastViewed: "2025-05-26T15:00:00.000Z",
      created: "2024-08-17T16:40:00.000Z"
    },
    {
      name: "Yet Again",
      id: "78897",
      description:
        "Here is a short description of this project and the things that you might find inside of it. Max 150 char.",
      lastViewed: "2025-05-25T18:30:00.000Z",
      created: "2024-07-25T14:30:00.000Z"
    },
    {
      name: "Final One",
      id: "91238",
      description:
        "Here is a short description of this project and the things that you might find inside of it. Max 150 char.",
      lastViewed: "2025-05-27T10:00:00.000Z",
      created: "2024-12-01T09:10:00.000Z"
    },
];

export const peopleData = [
  {
      id: 1,
      name: "Peter",
      image: "/images/peter.png",
      nickname: "Teton Country",
      visibility: "Public"
  },
  {
      id: 2,
      name: "Victor",
      image: "/images/victor.png",
      nickname: "New Cheese it!",
      visibility: "Project"
  },
  {
      id: 3,
      name: "Jaren (J2)",
      image: "/images/j2.png",
      nickname: "Minivan",
      visibility: "Public"
  },
  {
      id: 4,
      name: "Daniel",
      image: "/images/daniel.png",
      nickname: "Soccer games",
      visibility: "Public"
  },
  {
      id: 5,
      name: "Jason",
      image: "/images/jason.png",
      nickname: "I hate this place",
      visibility: "Private"
  },
  {
      id: 10,
      name: "Jeren (J1)",
      image: "/images/j1.png",
      nickname: "Mermaid Tails",
      visibility: "Project"
  },
  {
      id: 6,
      name: "Natalie",
      image: "/images/natalie.png",
      nickname: "What color?",
      visibility: "Private"
  },
  {
      id: 7,
      name: "Henry White",
      image: "/images/henry_white.jpg",
      nickname: "Hank",
      visibility: "Public"
  },
  {
      id: 8,
      name: "Isabella Martinez",
      image: "/images/isabella_martinez.jpg",
      nickname: "Izzy",
      visibility: "Public"
  },
  {
      id: 9,
      name: "Jack Davis",
      image: "/images/jack_davis.jpg",
      nickname: "JD",
      visibility: "Public"
  }
];