CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'deeplynx') THEN
            CREATE SCHEMA deeplynx;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.permissions (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        created_by text,
        created_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        modified_by text,
        modified_at timestamp without time zone,
        deleted_at timestamp without time zone,
        name text NOT NULL DEFAULT (''::text),
        CONSTRAINT permissions_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.projects (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        abbreviation text,
        created_by text,
        created_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        modified_by text,
        modified_at timestamp without time zone,
        deleted_at timestamp without time zone,
        CONSTRAINT projects_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.users (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        display_name text NOT NULL,
        email text NOT NULL,
        type text NOT NULL,
        created_by text,
        created_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        modified_by text,
        modified_at timestamp without time zone,
        deleted_at timestamp without time zone,
        CONSTRAINT users_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.classes (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        description text,
        uuid text,
        project_id bigint NOT NULL,
        created_by text,
        created_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        modified_by text,
        modified_at timestamp without time zone,
        deleted_at timestamp without time zone,
        CONSTRAINT classes_pkey PRIMARY KEY (id),
        CONSTRAINT classes_project_id_fkey FOREIGN KEY (project_id) REFERENCES deeplynx.projects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.data_sources (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        abbreviation text,
        type text,
        base_uri text,
        config jsonb,
        project_id bigint NOT NULL,
        created_by text,
        created_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        modified_by text,
        modified_at timestamp without time zone,
        deleted_at timestamp without time zone,
        CONSTRAINT data_sources_pkey PRIMARY KEY (id),
        CONSTRAINT data_sources_project_id_fkey FOREIGN KEY (project_id) REFERENCES deeplynx.projects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.roles (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        project_id bigint NOT NULL,
        created_by text,
        created_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        modified_by text,
        modified_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
        deleted_at timestamp without time zone,
        CONSTRAINT roles_pkey PRIMARY KEY (id),
        CONSTRAINT roles_project_id_fkey FOREIGN KEY (project_id) REFERENCES deeplynx.projects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.tags (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        project_id bigint NOT NULL,
        created_by text,
        created_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        modified_by text,
        modified_at timestamp without time zone,
        deleted_at timestamp without time zone,
        CONSTRAINT tags_pkey PRIMARY KEY (id),
        CONSTRAINT tags_project_id_fkey FOREIGN KEY (project_id) REFERENCES deeplynx.projects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.relationships (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        description text,
        uuid text,
        origin_id bigint NOT NULL,
        destination_id bigint NOT NULL,
        project_id bigint NOT NULL,
        created_by text,
        created_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        modified_by text,
        modified_at timestamp without time zone,
        deleted_at timestamp without time zone,
        CONSTRAINT relationships_pkey PRIMARY KEY (id),
        CONSTRAINT relationships_destination_id_fkey FOREIGN KEY (destination_id) REFERENCES deeplynx.classes (id) ON DELETE CASCADE,
        CONSTRAINT relationships_origin_id_fkey FOREIGN KEY (origin_id) REFERENCES deeplynx.classes (id) ON DELETE CASCADE,
        CONSTRAINT relationships_project_id_fkey FOREIGN KEY (project_id) REFERENCES deeplynx.projects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.records (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        uri text,
        properties jsonb NOT NULL,
        original_id text,
        name text,
        custom_id text,
        class_id bigint,
        class_name text,
        data_source_id bigint NOT NULL,
        project_id bigint NOT NULL,
        created_by text,
        created_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        modified_by text,
        modified_at timestamp without time zone,
        deleted_at timestamp without time zone,
        CONSTRAINT records_pkey PRIMARY KEY (id),
        CONSTRAINT records_class_id_fkey FOREIGN KEY (class_id) REFERENCES deeplynx.classes (id) ON DELETE CASCADE,
        CONSTRAINT records_data_source_id_fkey FOREIGN KEY (data_source_id) REFERENCES deeplynx.data_sources (id) ON DELETE CASCADE,
        CONSTRAINT records_project_id_fkey FOREIGN KEY (project_id) REFERENCES deeplynx.projects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.role_permissions (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        role_id bigint NOT NULL,
        permission_id bigint NOT NULL,
        action_type text NOT NULL,
        CONSTRAINT role_permissions_pkey PRIMARY KEY (id),
        CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES deeplynx.permissions (id) ON DELETE CASCADE,
        CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES deeplynx.roles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.user_projects (
        user_id bigint NOT NULL,
        project_id bigint NOT NULL,
        role_id bigint,
        CONSTRAINT user_projects_pkey PRIMARY KEY (user_id, project_id),
        CONSTRAINT user_projects_project_id_fkey FOREIGN KEY (project_id) REFERENCES deeplynx.projects (id) ON DELETE CASCADE,
        CONSTRAINT user_projects_role_id_fkey FOREIGN KEY (role_id) REFERENCES deeplynx.roles (id) ON DELETE CASCADE,
        CONSTRAINT user_projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES deeplynx.users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.record_mappings (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        record_params jsonb NOT NULL,
        class_id bigint,
        created_by text,
        created_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        modified_by text,
        modified_at timestamp without time zone,
        deleted_at timestamp without time zone,
        project_id bigint NOT NULL DEFAULT 0,
        tag_id bigint,
        CONSTRAINT record_mappings_pkey PRIMARY KEY (id),
        CONSTRAINT record_mappings_class_id_fkey FOREIGN KEY (class_id) REFERENCES deeplynx.classes (id),
        CONSTRAINT record_mappings_project_id_fkey FOREIGN KEY (project_id) REFERENCES deeplynx.projects (id) ON DELETE CASCADE,
        CONSTRAINT record_mappings_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES deeplynx.tags (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.edge_mappings (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        origin_params jsonb NOT NULL,
        destination_params jsonb NOT NULL,
        relationship_id bigint NOT NULL,
        origin_id bigint NOT NULL,
        destination_id bigint NOT NULL,
        project_id bigint NOT NULL,
        created_by text,
        created_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        modified_by text,
        modified_at timestamp without time zone,
        deleted_at timestamp without time zone,
        CONSTRAINT edge_mappings_pkey PRIMARY KEY (id),
        CONSTRAINT edge_mappings_destination_id_fkey FOREIGN KEY (destination_id) REFERENCES deeplynx.classes (id) ON DELETE CASCADE,
        CONSTRAINT edge_mappings_origin_id_fkey FOREIGN KEY (origin_id) REFERENCES deeplynx.classes (id) ON DELETE CASCADE,
        CONSTRAINT edge_mappings_project_id_fkey FOREIGN KEY (project_id) REFERENCES deeplynx.projects (id) ON DELETE CASCADE,
        CONSTRAINT edge_mappings_relationship_id_fkey FOREIGN KEY (relationship_id) REFERENCES deeplynx.relationships (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.edges (
        origin_id bigint NOT NULL,
        destination_id bigint NOT NULL,
        properties jsonb,
        relationship_id bigint,
        relationship_name text,
        data_source_id bigint,
        project_id bigint NOT NULL DEFAULT 0,
        CONSTRAINT edges_pkey PRIMARY KEY (origin_id, destination_id),
        CONSTRAINT edges_data_source_id_fkey FOREIGN KEY (data_source_id) REFERENCES deeplynx.data_sources (id),
        CONSTRAINT edges_destination_id_fkey FOREIGN KEY (destination_id) REFERENCES deeplynx.records (id) ON DELETE CASCADE,
        CONSTRAINT edges_origin_id_fkey FOREIGN KEY (origin_id) REFERENCES deeplynx.records (id) ON DELETE CASCADE,
        CONSTRAINT edges_project_id_fkey FOREIGN KEY (project_id) REFERENCES deeplynx.projects (id) ON DELETE CASCADE,
        CONSTRAINT edges_relationship_id_fkey FOREIGN KEY (relationship_id) REFERENCES deeplynx.relationships (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.record_tags (
        record_id bigint NOT NULL,
        tag_id bigint NOT NULL,
        CONSTRAINT record_tags_pkey PRIMARY KEY (record_id, tag_id),
        CONSTRAINT record_tags_record_id_fkey FOREIGN KEY (record_id) REFERENCES deeplynx.records (id) ON DELETE CASCADE,
        CONSTRAINT record_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES deeplynx.tags (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE TABLE deeplynx.role_resources (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        role_id bigint NOT NULL,
        data_source_id bigint,
        tag_id bigint,
        record_id bigint,
        has_access boolean DEFAULT TRUE,
        CONSTRAINT role_resources_pkey PRIMARY KEY (id),
        CONSTRAINT role_resources_data_source_id_fkey FOREIGN KEY (data_source_id) REFERENCES deeplynx.data_sources (id) ON DELETE CASCADE,
        CONSTRAINT role_resources_record_id_fkey FOREIGN KEY (record_id) REFERENCES deeplynx.records (id) ON DELETE CASCADE,
        CONSTRAINT role_resources_role_id_fkey FOREIGN KEY (role_id) REFERENCES deeplynx.roles (id) ON DELETE CASCADE,
        CONSTRAINT role_resources_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES deeplynx.tags (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_classes_id ON deeplynx.classes (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_classes_project_id ON deeplynx.classes (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_classes_uuid ON deeplynx.classes (uuid);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_data_sources_id ON deeplynx.data_sources (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_data_sources_project_id ON deeplynx.data_sources (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_edge_mappings_destination_id ON deeplynx.edge_mappings (destination_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_edge_mappings_id ON deeplynx.edge_mappings (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_edge_mappings_origin_id ON deeplynx.edge_mappings (origin_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_edge_mappings_project_id ON deeplynx.edge_mappings (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_edge_mappings_relationship_id ON deeplynx.edge_mappings (relationship_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_edges_data_source_id ON deeplynx.edges (data_source_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_edges_destination_id ON deeplynx.edges (destination_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_edges_origin_id ON deeplynx.edges (origin_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_edges_project_id ON deeplynx.edges (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_edges_relationship_id ON deeplynx.edges (relationship_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_permissions_id ON deeplynx.permissions (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_projects_id ON deeplynx.projects (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_record_mappings_class_id ON deeplynx.record_mappings (class_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_record_mappings_id ON deeplynx.record_mappings (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_record_mappings_project_id ON deeplynx.record_mappings (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_record_mappings_tag_id ON deeplynx.record_mappings (tag_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_record_tags_record_id ON deeplynx.record_tags (record_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_record_tags_tag_id ON deeplynx.record_tags (tag_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_records_class_id ON deeplynx.records (class_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_records_class_name ON deeplynx.records (class_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_records_data_source_id ON deeplynx.records (data_source_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_records_id ON deeplynx.records (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_records_name ON deeplynx.records (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_records_original_id ON deeplynx.records (original_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_records_project_id ON deeplynx.records (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_records_properties ON deeplynx.records USING gin (properties);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_relationships_destination_id ON deeplynx.relationships (destination_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_relationships_id ON deeplynx.relationships (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_relationships_origin_id ON deeplynx.relationships (origin_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_relationships_project_id ON deeplynx.relationships (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_relationships_uuid ON deeplynx.relationships (uuid);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_role_permissions_action_type ON deeplynx.role_permissions (action_type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_role_permissions_permission_id ON deeplynx.role_permissions (permission_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_role_permissions_role_id ON deeplynx.role_permissions (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_role_resources_data_source_id ON deeplynx.role_resources (data_source_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_role_resources_record_id ON deeplynx.role_resources (record_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_role_resources_role_id ON deeplynx.role_resources (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_role_resources_tag_id ON deeplynx.role_resources (tag_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_roles_id ON deeplynx.roles (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_roles_project_id ON deeplynx.roles (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_tags_id ON deeplynx.tags (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_tags_project_id ON deeplynx.tags (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_user_projects_project_id ON deeplynx.user_projects (project_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_user_projects_role_id ON deeplynx.user_projects (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_user_projects_user_id ON deeplynx.user_projects (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    CREATE INDEX idx_users_id ON deeplynx.users (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509141317_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250509141317_InitialCreate', '10.0.0-preview.5.25277.114');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250514144411_AddEdgeAuditColumns') THEN
    ALTER TABLE deeplynx.edges ADD created_at timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250514144411_AddEdgeAuditColumns') THEN
    ALTER TABLE deeplynx.edges ADD created_by text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250514144411_AddEdgeAuditColumns') THEN
    ALTER TABLE deeplynx.edges ADD deleted_at timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250514144411_AddEdgeAuditColumns') THEN
    ALTER TABLE deeplynx.edges ADD modified_at timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250514144411_AddEdgeAuditColumns') THEN
    ALTER TABLE deeplynx.edges ADD modified_by text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250514144411_AddEdgeAuditColumns') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250514144411_AddEdgeAuditColumns', '10.0.0-preview.5.25277.114');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250520201541_AddEdgeId') THEN
    ALTER TABLE deeplynx.edges DROP CONSTRAINT edges_pkey;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250520201541_AddEdgeId') THEN
    ALTER TABLE deeplynx.edges DROP CONSTRAINT edges_data_source_id_fkey;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250520201541_AddEdgeId') THEN
    UPDATE deeplynx.edges SET data_source_id = 0 WHERE data_source_id IS NULL;
    ALTER TABLE deeplynx.edges ALTER COLUMN data_source_id SET NOT NULL;
    ALTER TABLE deeplynx.edges ALTER COLUMN data_source_id SET DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250520201541_AddEdgeId') THEN
    ALTER TABLE deeplynx.edges ADD id bigint GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250520201541_AddEdgeId') THEN
    CREATE INDEX idx_edges_id ON deeplynx.edges (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250520201541_AddEdgeId') THEN
    ALTER TABLE deeplynx.edges ADD CONSTRAINT edges_pkey PRIMARY KEY (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250520201541_AddEdgeId') THEN
    ALTER TABLE deeplynx.edges ADD CONSTRAINT edges_data_source_id_fkey FOREIGN KEY (data_source_id) REFERENCES deeplynx.data_sources (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250520201541_AddEdgeId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250520201541_AddEdgeId', '10.0.0-preview.5.25277.114');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604174041_AddProjectDescription') THEN
    ALTER TABLE deeplynx.projects ADD description text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604174041_AddProjectDescription') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250604174041_AddProjectDescription', '10.0.0-preview.5.25277.114');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604191847_AddDataSourceDescription') THEN
    ALTER TABLE deeplynx.data_sources ADD description text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250604191847_AddDataSourceDescription') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250604191847_AddDataSourceDescription', '10.0.0-preview.5.25277.114');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250611163650_FixRecordMappingsConstraint') THEN
    ALTER TABLE deeplynx.record_mappings DROP CONSTRAINT record_mappings_class_id_fkey;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250611163650_FixRecordMappingsConstraint') THEN
    ALTER TABLE deeplynx.record_mappings ADD CONSTRAINT record_mappings_class_id_fkey FOREIGN KEY (class_id) REFERENCES deeplynx.classes (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250611163650_FixRecordMappingsConstraint') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250611163650_FixRecordMappingsConstraint', '10.0.0-preview.5.25277.114');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619133859_SetArchivedAt') THEN
    ALTER TABLE deeplynx.users RENAME COLUMN deleted_at TO archived_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619133859_SetArchivedAt') THEN
    ALTER TABLE deeplynx.tags RENAME COLUMN deleted_at TO archived_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619133859_SetArchivedAt') THEN
    ALTER TABLE deeplynx.roles RENAME COLUMN deleted_at TO archived_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619133859_SetArchivedAt') THEN
    ALTER TABLE deeplynx.relationships RENAME COLUMN deleted_at TO archived_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619133859_SetArchivedAt') THEN
    ALTER TABLE deeplynx.records RENAME COLUMN deleted_at TO archived_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619133859_SetArchivedAt') THEN
    ALTER TABLE deeplynx.record_mappings RENAME COLUMN deleted_at TO archived_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619133859_SetArchivedAt') THEN
    ALTER TABLE deeplynx.projects RENAME COLUMN deleted_at TO archived_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619133859_SetArchivedAt') THEN
    ALTER TABLE deeplynx.permissions RENAME COLUMN deleted_at TO archived_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619133859_SetArchivedAt') THEN
    ALTER TABLE deeplynx.edges RENAME COLUMN deleted_at TO archived_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619133859_SetArchivedAt') THEN
    ALTER TABLE deeplynx.edge_mappings RENAME COLUMN deleted_at TO archived_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619133859_SetArchivedAt') THEN
    ALTER TABLE deeplynx.data_sources RENAME COLUMN deleted_at TO archived_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619133859_SetArchivedAt') THEN
    ALTER TABLE deeplynx.classes RENAME COLUMN deleted_at TO archived_at;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619133859_SetArchivedAt') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250619133859_SetArchivedAt', '10.0.0-preview.5.25277.114');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619140545_AddArchivalStoredProcedures') THEN

                    CREATE OR REPLACE PROCEDURE deeplynx.archive_project(arc_project_id INTEGER, arc_time TIMESTAMP WITHOUT TIME ZONE)
                    LANGUAGE plpgsql AS $$
                    BEGIN
                        UPDATE deeplynx.projects SET archived_at = arc_time WHERE id = arc_project_id;
                        UPDATE deeplynx.data_sources SET archived_at = arc_time WHERE project_id = arc_project_id;
                        UPDATE deeplynx.records SET archived_at = arc_time WHERE project_id = arc_project_id;
                        UPDATE deeplynx.edges SET archived_at = arc_time WHERE project_id = arc_project_id;
                        UPDATE deeplynx.classes SET archived_at = arc_time WHERE project_id = arc_project_id;
                        UPDATE deeplynx.relationships SET archived_at = arc_time WHERE project_id = arc_project_id;
                        UPDATE deeplynx.edge_mappings SET archived_at = arc_time WHERE project_id = arc_project_id;
                        UPDATE deeplynx.record_mappings SET archived_at = arc_time WHERE project_id = arc_project_id;
                        UPDATE deeplynx.tags SET archived_at = arc_time WHERE project_id = arc_project_id;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619140545_AddArchivalStoredProcedures') THEN

                    CREATE OR REPLACE PROCEDURE deeplynx.archive_record(arc_record_id INTEGER, arc_time TIMESTAMP WITHOUT TIME ZONE)
                    LANGUAGE plpgsql AS $$
                    BEGIN
                        UPDATE deeplynx.records SET archived_at = arc_time WHERE id = arc_record_id;
                        UPDATE deeplynx.edges SET archived_at = arc_time WHERE origin_id = arc_record_id OR destination_id = arc_record_id;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619140545_AddArchivalStoredProcedures') THEN

                    CREATE OR REPLACE PROCEDURE deeplynx.archive_class(arc_class_id INTEGER, arc_time TIMESTAMP WITHOUT TIME ZONE)
                    LANGUAGE plpgsql AS $$
                    BEGIN
                        UPDATE deeplynx.classes SET archived_at = arc_time WHERE id = arc_class_id;
                        UPDATE deeplynx.relationships SET archived_at = arc_time WHERE origin_id = arc_class_id OR destination_id = arc_class_id;
                        UPDATE deeplynx.edge_mappings SET archived_at = arc_time WHERE origin_id = arc_class_id OR destination_id = arc_class_id;
                        UPDATE deeplynx.record_mappings SET archived_at = arc_time WHERE class_id = arc_class_id;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619140545_AddArchivalStoredProcedures') THEN

                    CREATE OR REPLACE PROCEDURE deeplynx.archive_relationship(arc_rel_id INTEGER, arc_time TIMESTAMP WITHOUT TIME ZONE)
                    LANGUAGE plpgsql AS $$
                    BEGIN
                        UPDATE deeplynx.relationships SET archived_at = arc_time WHERE id = arc_rel_id;
                        UPDATE deeplynx.edge_mappings SET archived_at = arc_time WHERE relationship_id = arc_rel_id;
                    END;
                    $$;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619140545_AddArchivalStoredProcedures') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250619140545_AddArchivalStoredProcedures', '10.0.0-preview.5.25277.114');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619162350_RemoveRoleTables') THEN
    DROP TABLE deeplynx.role_permissions;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619162350_RemoveRoleTables') THEN
    DROP TABLE deeplynx.role_resources;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619162350_RemoveRoleTables') THEN
    DROP TABLE deeplynx.user_projects;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619162350_RemoveRoleTables') THEN
    DROP TABLE deeplynx.permissions;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619162350_RemoveRoleTables') THEN
    DROP TABLE deeplynx.roles;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619162350_RemoveRoleTables') THEN
    DROP TABLE deeplynx.users;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250619162350_RemoveRoleTables') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250619162350_RemoveRoleTables', '10.0.0-preview.5.25277.114');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250624205605_AddUserTable') THEN
    CREATE TABLE deeplynx.users (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        email text NOT NULL,
        password text,
        archived_at timestamp without time zone,
        CONSTRAINT users_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250624205605_AddUserTable') THEN
    CREATE INDEX idx_users_email ON deeplynx.users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250624205605_AddUserTable') THEN
    CREATE INDEX idx_users_id ON deeplynx.users (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250624205605_AddUserTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250624205605_AddUserTable', '10.0.0-preview.5.25277.114');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250702192420_UpdateDataSource') THEN
    ALTER TABLE deeplynx.data_sources ALTER COLUMN id RESTART WITH 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250702192420_UpdateDataSource') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250702192420_UpdateDataSource', '10.0.0-preview.5.25277.114');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250702195735_AddRecordMappingForeignKey') THEN
    ALTER TABLE deeplynx.records DROP CONSTRAINT records_class_id_fkey;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250702195735_AddRecordMappingForeignKey') THEN
    ALTER TABLE deeplynx.records ADD mapping_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250702195735_AddRecordMappingForeignKey') THEN
    CREATE INDEX idx_records_mapping_id ON deeplynx.records (mapping_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250702195735_AddRecordMappingForeignKey') THEN
    ALTER TABLE deeplynx.records ADD CONSTRAINT records_class_id_fkey FOREIGN KEY (class_id) REFERENCES deeplynx.classes (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250702195735_AddRecordMappingForeignKey') THEN
    ALTER TABLE deeplynx.records ADD CONSTRAINT records_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES deeplynx.record_mappings (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250702195735_AddRecordMappingForeignKey') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250702195735_AddRecordMappingForeignKey', '10.0.0-preview.5.25277.114');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250702210556_UpdateEdgesTable') THEN
    ALTER TABLE deeplynx.edges DROP COLUMN properties;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250702210556_UpdateEdgesTable') THEN
    ALTER TABLE deeplynx.edges ADD mapping_id bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250702210556_UpdateEdgesTable') THEN
    CREATE INDEX idx_edges_mapping_id ON deeplynx.edges (mapping_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250702210556_UpdateEdgesTable') THEN
    ALTER TABLE deeplynx.edges ADD CONSTRAINT edges_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES deeplynx.edge_mappings (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250702210556_UpdateEdgesTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250702210556_UpdateEdgesTable', '10.0.0-preview.5.25277.114');
    END IF;
END $EF$;
COMMIT;

