name: Preflight Build Check

on:
  pull_request:
    branches: ["develop", "main"]

jobs:
  build-check:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build Test
        env:
          ACR_SP_USER: ${{ secrets.CI_SP_USER }}
          ACR_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
          ACR_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
          ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
          ACR_REGISTRY: ${{ secrets.CI_REGISTRY }}
          NEXT_PUBLIC_OKTA_CLIENT_ID: ${{ vars.NEXT_PUBLIC_OKTA_CLIENT_ID }}
          NEXT_PUBLIC_OKTA_ISSUER: ${{ vars.NEXT_PUBLIC_OKTA_ISSUER }}
          NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_REDIRECT_LINK: ${{ vars.NEXT_PUBLIC_REDIRECT_LINK }}
          OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
          BACKEND_BASE_URL: ${{ vars.BACKEND_BASE_URL }}
        run: |
          cd $GITHUB_WORKSPACE
          az cloud set --name AzureUSGovernment
          az login --service-principal -u $ACR_SP_USER -p $ACR_SP_PASSWORD --tenant $ACR_SP_TENANT
          az account set --subscription $ACR_SUBSCRIPTION

          # Build app image without pushing to registry
          az acr build --registry $ACR_REGISTRY \
            --no-push \
            --file Dockerfiles/Dockerfile.app \
            --build-arg NEXT_PUBLIC_OKTA_CLIENT_ID="${{ vars.NEXT_PUBLIC_OKTA_CLIENT_ID }}" \
            --build-arg NEXT_PUBLIC_OKTA_ISSUER="${{ vars.NEXT_PUBLIC_OKTA_ISSUER }}" \
            --build-arg NEXT_PUBLIC_API_URL="${{ vars.NEXT_PUBLIC_API_URL }}" \
            --b