
 #github Sandbox/Test workflow
name: Build Sandbox/Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'sandbox'

  push:
    branches: ["sandbox"]

jobs:
  build:
    runs-on: [self-hosted]
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug Dockerfile Build
        env:
          ACR_SP_USER: ${{ secrets.CI_SP_USER }}
          ACR_SP_PASSWORD: ${{ secrets.CI_SP_PASSWORD }}
          ACR_REGISTRY: ${{ secrets.CI_REGISTRY }}
          ACR_PATH: ${{ secrets.CI_REGISTRY_PATH }}
          ACR_SP_TENANT: ${{ secrets.CI_SP_TENANT }}
          ACR_SUBSCRIPTION: ${{ secrets.CI_ACR_SUBSCRIPTION }}
          GITHUB_RUN_NUMBER: ${{ github.RUN_NUMBER }}
          OKTA_CLIENT_ID: ${{ vars.OKTA_CLIENT_ID }}
          OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
          OKTA_ISSUER: ${{ vars.OKTA_ISSUER }}
          JWT_ISSUER: ${{vars.JWT_ISSUER}}
          JWT_AUDIENCE: ${{vars.JWT_AUDIENCE}}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          REDIRECT_LINK: ${{ vars.REDIRECT_LINK }}
          SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
          BACKEND_BASE_URL: ${{ vars.BACKEND_BASE_URL }}
          DISABLE_FRONTEND_AUTHENTICATION: ${{ vars.DISABLE_FRONTEND_AUTHENTICATION }}
          HOSTED_LINK: ${{ vars.HOSTED_LINK }}
        run: |
          az acr build --registry "$ACR_REGISTRY" \
            --image "$ACR_PATH:debug-env-${GITHUB_RUN_NUMBER}" \
            --file Dockerfile.sandbox \
            --build-arg OKTA_CLIENT_ID="$OKTA_CLIENT_ID" \
            --build-arg OKTA_ISSUER="$OKTA_ISSUER" \
            --build-arg NEXTAUTH_URL="$NEXTAUTH_URL" \
            --build-arg REDIRECT_LINK="$REDIRECT_LINK" \
            --build-arg OKTA_CLIENT_SECRET="$OKTA_CLIENT_SECRET" \
            --build-arg AUTH_SECRET="$AUTH_SECRET" \
            --build-arg NEXTAUTH_SECRET="$NEXTAUTH_SECRET" \
            --build-arg SERVICE_TOKEN="$SERVICE_TOKEN" \
            --build-arg BACKEND_BASE_URL="$BACKEND_BASE_URL" \
            --build-arg DISABLE_FRONTEND_AUTHENTICATION="$DISABLE_FRONTEND_AUTHENTICATION" \
            .
